#!/usr/bin/env bash
# Install and configure HAproxy.

#Update the system
sudo apt-get update -y

# Install HAproxy
sudo apt-get install -y haproxy

# Configure HAproxy
backend="backend web_backend\n\
\tbalance roundrobin\n\
\tserver 199831-web-01 34.204.60.232:80 check\n\
\tserver 199831-web-02 54.160.126.236:80 check\n"

frontend="frontend web_frontend\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web_backend\n"

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo sed -i "$ a ${backend}\n${frontend}" /etc/haproxy/haproxy.cfg

#Enable HAProxy init script
sudo sed -i "$ a ENABLED=1" /etc/default/haproxy

# Restart HAproxy
sudo service haproxy start
