#!/usr/bin/env bash
# This script does the following:
# 	Creates the file /var/run/myscript.pid containing its PID
# 	Displays "To infinity and beyond" indefinitely.
# 	Displays "I hate the kill command" when it receives a SIGTERM
# 	Displays "Y U no love me?!" when receiving a SIGINT signal
# 	Deletes the file /var/run/myscript.pid and terminates when receiving a SIGQUIT
# 	or SIGTERM signal.

pgrep -f 100-process_and_pid_file > /var/run/myscript.pid

trap sigint_capture SIGINT
trap sigterm_capture SIGTERM
trap sigquit_capture SIGQUIT

function sigint_capture() {
	echo "Y U no love me?!"
}

function sigterm_capture() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

function sigquit_capture() {
	rm /var/run/myscript.pid
	exit
}

while true
do
	echo "To infinity and beyond"
	sleep 2
done
