#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a sleep 2 between each
# iteration and "I am invincible!!!" when receiving a SIGTERM signal.

trap sigterm_capture SIGTERM

function sigterm_capture() {
	echo "I am invincible!!!"
}

while true
do
	echo "To infinity and beyond"
	sleep 2
done
