#!/usr/bin/env bash
# Displays numbers from 1 to 100.
# 	Displays "FizzBuzz" when the number is a multiple of 3 and 5.
# 	Displays "Fizz" when number is a multiple of 3.
# 	Displays "Buzz" when number is a multiple of 5.
# 	Otherwise displays the number.

count=1

while [ $count -le 100 ]
do
	text=""

	if [ $((count % 3)) -eq 0 ]
	then
		text+="Fizz"
	fi

	if [ $((count % 5)) -eq 0 ]
	then
		text+="Buzz"
	fi

	if [ -n "$text" ]
	then
		echo "$text"
	else
		echo "$count"
	fi

	((count++))
done
