#!/usr/bin/env bash
# Displays the content of the file "/etc/passwd".
# 	only displays username, user id and home directory of user.

file="/etc/passwd"

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "$file"
