#!/usr/bin/env bash
# Displays the time for 12 hours 59 minutes:
# 	Hours: from 0 to 12
# 	Minutes: from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"

	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done

	minute=1
	((hour++))
done
