#!/usr/bin/env bash
# Displays the content of the current directory in a list format,
# where only the part of the name after the first dash is displayed.

content=$(ls)

for i in ${content}
do
	echo "$i" | cut -d "-" -f 2 -s
done
